# ----------------------------------------------------------------------------
# Modo: redimensionar
# ----------------------------------------------------------------------------
mode "resize" {
    # hjkl encogen/agrandan el ancho o alto
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px
    # Igual con las flechas
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px
    # Volver al modo normal
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"
