# ~/.config/foot/foot.ini
[main]
font=monospace:size=10
term=xterm-256color

cursor-style=beam

[cursor]
color=8497f7

[colors]
background=1e1e2e
foreground=d0d0d0
selection-foreground=1e1e2e
selection-background=8497f7
alpha=0.9

# (paleta base catppuccin/mocha ligera)
regular0=1e1e2e
regular1=ff6e6e
regular2=6edb6e
regular3=ffff7a
regular4=8497f7
regular5=ff9ef5
regular6=6edbf7
regular7=ffffff
bright0=7f7f7f
bright1=ff6e6e
bright2=6edb6e
bright3=ffff7a
bright4=8497f7
bright5=ff9ef5
bright6=6edbf7
bright7=ffffff