# ----------------------------------------------------------------------------
# Atajos: aplicaciones
# ----------------------------------------------------------------------------
    # Terminal
    bindsym $mod+Return exec $terminal

    # Cerrar la ventana enfocada
    bindsym $mod+Shift+q kill
