# ----------------------------------------------------------------------------
# Atajos: aplicaciones
# ----------------------------------------------------------------------------
    # Terminal
    bindsym $mod+Return exec $terminal

    # Cerrar la ventana enfocada
    bindsym $mod+Shift+q kill

    # Gestor de fondos de pantalla (azote, GUI para swaybg)
    bindsym $mod+Shift+w exec azote
