# ----------------------------------------------------------------------------
# Atajos: teclas multimedia (XF86)
# ----------------------------------------------------------------------------
    # Silenciar el micrófono
    bindsym XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle

    # Brillo: ajustar + aviso visual con wob
    bindsym XF86MonBrightnessDown exec brightnessctl -q set 5%- && ( echo $((`brightnessctl get` * 100 / `brightnessctl m`)) > $SWAYSOCK.wob )
    bindsym XF86MonBrightnessUp exec brightnessctl -q set +5% && ( echo $((`brightnessctl get` * 100 / `brightnessctl m`)) > $SWAYSOCK.wob )

    # Volumen: pamixer + aviso con wob (cap al 100%)
    bindsym XF86AudioRaiseVolume exec pamixer --allow-boost -ui 2 && dc -e "[`pamixer --get-volume`]sM 100d `pamixer --get-volume`<Mp" > $SWAYSOCK.wob
    bindsym XF86AudioLowerVolume exec pamixer --allow-boost -ud 2 && dc -e "[`pamixer --get-volume`]sM 100d `pamixer --get-volume`<Mp" > $SWAYSOCK.wob
    bindsym XF86AudioMute exec pamixer --toggle-mute && ( pamixer --get-mute && echo 0 > $SWAYSOCK.wob )

    # Controles de reproducción
    bindsym --no-warn XF86AudioPlay exec playerctl play-pause
    bindsym --no-warn XF86AudioNext exec playerctl next
    bindsym --no-warn XF86AudioPrev exec playerctl previous

    # Historial del portapapeles (cliphist) en wofi.
    bindsym $mod+Shift+v exec ~/.config/sway/scripts/clipboard.sh

    # Grabación de video: la misma tecla inicia y detiene (toggle)
    bindsym $mod+Shift+r exec ~/.config/sway/scripts/swpy-recorder.sh full
    bindsym $mod+Shift+a exec ~/.config/sway/scripts/swpy-recorder.sh area
