# Ajustes de usuario sobre la base openSUSEway.
# Se carga después de /etc/sway/config.d/* por el include del config principal.

### =========================
### Layout de teclado
### =========================

input * {
    xkb_layout "latam"
}

### =========================
### Monitores
### =========================

output HDMI-A-2 resolution 1920x1080 position 0,0
output HDMI-A-1 resolution 1920x1080 position 1920,0