# ----------------------------------------------------------------------------
# Entrada: teclado y touchpad
# ----------------------------------------------------------------------------
# Layout latinoamericano (teclado físico)
input "type:keyboard" {
    xkb_layout "latam"
}
# Opciones comunes para touchpads genéricos
input "type:touchpad" {
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
}
