# ----------------------------------------------------------------------------
# Notificaciones (swaync)
# ----------------------------------------------------------------------------
    # Mostrar/ocultar el centro de notificaciones
    set $toggle_notification "swaync-client -t -sw"
    bindsym $mod+Shift+n exec $toggle_notification
