# ----------------------------------------------------------------------------
# Capturas de pantalla ($mod+Print)
# ----------------------------------------------------------------------------

    # Áreas de interés
    set $selected_window swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp
    set $focused_window swaymsg -t get_tree | jq -j '.. | select(.type?) | select(.focused).rect | "\(.x),\(.y) \(.width)x\(.height)"'
    set $focused_output swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name'

    # Capturas (archivo o portapapeles con Ctrl)
    set $screenshot_full grim
    set $screenshot_full_clipboard grim - | wl-copy
    set $screenshot_selected_window $selected_window | grim -g-
    set $screenshot_selected_window_clipboard $selected_window | grim -g- - | wl-copy
    set $screenshot_selected_area slurp | grim -g-
    set $screenshot_selected_area_clipboard slurp | grim -g- - | wl-copy
    set $screenshot_focused_window $focused_window | grim -g-
    set $screenshot_focused_window_clipboard $focused_window | grim -g- - | wl-copy
    set $screenshot_focused_output grim -o $($focused_output)
    set $screenshot_focused_output_clipboard grim -o $($focused_output) - | wl-copy

    # Menú de captura: (f) completa, (s) ventana, (a) área, (w) ventana
    # enfocada, (o) salida enfocada. Ctrl+<tecla> guarda en portapapeles.
    set $screenshot "Screenshot: (f) full, (s) select window, (a) select area, (w) focused window, (o) focused output [Ctrl+ saves to clipboard]"
    mode $screenshot {
        bindsym f exec $screenshot_full; mode "default"
        bindsym Ctrl+f exec $screenshot_full_clipboard; mode "default"
        bindsym s exec $screenshot_selected_window; mode "default"
        bindsym Ctrl+s exec $screenshot_selected_window_clipboard; mode "default"
        bindsym a exec $screenshot_selected_area; mode "default"
        bindsym Ctrl+a exec $screenshot_selected_area_clipboard; mode "default"
        bindsym w exec $screenshot_focused_window; mode "default"
        bindsym Ctrl+w exec $screenshot_focused_window_clipboard; mode "default"
        bindsym o exec $screenshot_focused_output; mode "default"
        bindsym Ctrl+o exec $screenshot_focused_output_clipboard; mode "default"

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+Print mode "default"
    }
    bindsym $mod+Print mode $screenshot
