# ----------------------------------------------------------------------------
# Variables
# ----------------------------------------------------------------------------
set $mod Mod4
# Direcciones tipo vim (fila central)
set $left h
set $down j
set $up k
set $right l
# Terminal
set $term foot
# Lanzador de aplicaciones
set $menu wofi --conf=/etc/wofi/config --style=/etc/wofi/style.css
# Bloqueo de pantalla (config de openSUSEway)
set $screenlock 'swaylock --config /etc/swaylock/openSUSEway.conf'
# OSD de volumen/brillo
set $wob wob --config /etc/sway/wob/wob.ini
