# Configuración de la fuente

font_family         Iosevka NFM
bold_font           Iosevka NFM Bold
italic_font         Iosevka NFM Italic
bold_italic_font    Iosevka NFM Bold Italic

font_size 12

# Configuración del Fondo

background_opacity 0.80
background_image none
